DROP TABLE IF EXISTS REACTION;
CREATE TABLE REACTION (
    ID SERIAL PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    TWEET_ID INTEGER NOT NULL,
    TWEET_USER_ID INTEGER NOT NULL,
    TYPE VARCHAR(255),
    VOTE BOOLEAN,
    COMMENT text,
    CREATE_TIME_STAMP text
);